USE [master]
GO

/****** Object:  Database [Zadanie1-2]    Script Date: 21.02.2022 0:07:02 ******/
CREATE DATABASE [Zadanie1-2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Задание 1 - 2', FILENAME = N'C:\Users\asya1\Desktop\MSSQL15.SQLEXPRESS\MSSQL\DATA\Задание 1 - 2 .mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Задание 1 - 2 _log', FILENAME = N'C:\Users\asya1\Desktop\MSSQL15.SQLEXPRESS\MSSQL\DATA\Задание 1 - 2 _log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Zadanie1-2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Zadanie1-2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Zadanie1-2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Zadanie1-2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Zadanie1-2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Zadanie1-2] SET ARITHABORT OFF 
GO

ALTER DATABASE [Zadanie1-2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Zadanie1-2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Zadanie1-2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Zadanie1-2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Zadanie1-2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Zadanie1-2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Zadanie1-2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Zadanie1-2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Zadanie1-2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Zadanie1-2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Zadanie1-2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Zadanie1-2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Zadanie1-2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Zadanie1-2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Zadanie1-2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Zadanie1-2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Zadanie1-2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Zadanie1-2] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Zadanie1-2] SET  MULTI_USER 
GO

ALTER DATABASE [Zadanie1-2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Zadanie1-2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Zadanie1-2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Zadanie1-2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Zadanie1-2] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Zadanie1-2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Zadanie1-2] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Zadanie1-2] SET  READ_WRITE 
GO


